package udl.prac3.pruebasunitarias.medicalconsultation;

public enum dayMoment {
    BEFOREBREAKFAST, DURINGBREAKFAST, AFTERBREAKFAST, BEFORELUNCH,
    DURINGLUNCH, AFTERLUNCH, BEFOREDINNER, DURINGDINNER, AFTERDINNER,
    BEFOREMEALS, DURINGMEALS, AFTERMEALS;
}
